-- Week 13 Community Starter Requests and Joinable Needs
--
-- Adds community-seeding requests that many people can join through "Join Need".
-- These are not real user posts. They are starter/demo needs for onboarding,
-- discovery, and local community activation.

ALTER TABLE public.help_requests
  ADD COLUMN IF NOT EXISTS short_description TEXT,
  ADD COLUMN IF NOT EXISTS full_description TEXT,
  ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  ADD COLUMN IF NOT EXISTS difficulty TEXT NOT NULL DEFAULT 'medium',
  ADD COLUMN IF NOT EXISTS estimated_people_who_may_benefit TEXT,
  ADD COLUMN IF NOT EXISTS community_request BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS allow_join_need BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS join_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS helper_count INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS goodwill_impact_score INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tag_credit_bonus INTEGER NOT NULL DEFAULT 0;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'help_requests_difficulty_check'
  ) THEN
    ALTER TABLE public.help_requests
      ADD CONSTRAINT help_requests_difficulty_check
      CHECK (difficulty IN ('low', 'medium', 'high'));
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'help_requests_community_counts_check'
  ) THEN
    ALTER TABLE public.help_requests
      ADD CONSTRAINT help_requests_community_counts_check
      CHECK (
        join_count >= 0
        AND helper_count >= 0
        AND goodwill_impact_score BETWEEN 0 AND 100
        AND tag_credit_bonus >= 0
      );
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.calculate_tag_credit_bonus(p_tags TEXT[])
RETURNS INTEGER AS $$
BEGIN
  IF COALESCE(array_length(p_tags, 1), 0) >= 2 THEN
    RETURN 10;
  END IF;

  RETURN 0;
END;
$$ LANGUAGE plpgsql IMMUTABLE;

CREATE OR REPLACE FUNCTION public.set_help_request_tag_credit_bonus()
RETURNS trigger AS $$
BEGIN
  NEW.tags := COALESCE(NEW.tags, '{}'::TEXT[]);
  NEW.tag_credit_bonus := public.calculate_tag_credit_bonus(NEW.tags);
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_help_request_tag_credit_bonus_trigger ON public.help_requests;
CREATE TRIGGER set_help_request_tag_credit_bonus_trigger
  BEFORE INSERT OR UPDATE OF tags ON public.help_requests
  FOR EACH ROW EXECUTE PROCEDURE public.set_help_request_tag_credit_bonus();

CREATE TABLE IF NOT EXISTS public.community_starter_requests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL UNIQUE,
  short_description TEXT NOT NULL,
  full_description TEXT NOT NULL,
  category TEXT NOT NULL CHECK (
    category IN (
      'Education',
      'Career',
      'Technology',
      'Health Awareness',
      'Blood Donation Awareness',
      'Volunteering',
      'Environment',
      'Transportation',
      'Food Support',
      'Community Events',
      'Elderly Assistance',
      'Mental Wellbeing',
      'Financial Literacy',
      'Entrepreneurship',
      'Government Services',
      'Skill Development'
    )
  ),
  tags TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  difficulty TEXT NOT NULL CHECK (difficulty IN ('low', 'medium', 'high')),
  estimated_people_who_may_benefit TEXT NOT NULL,
  community_request BOOLEAN NOT NULL DEFAULT true,
  allow_join_need BOOLEAN NOT NULL DEFAULT true,
  join_count INTEGER NOT NULL DEFAULT 0 CHECK (join_count BETWEEN 0 AND 50),
  helper_count INTEGER NOT NULL DEFAULT 0 CHECK (helper_count BETWEEN 0 AND 10),
  goodwill_impact_score INTEGER NOT NULL DEFAULT 0 CHECK (goodwill_impact_score BETWEEN 0 AND 100),
  tag_credit_bonus INTEGER NOT NULL DEFAULT 0 CHECK (tag_credit_bonus >= 0),
  status TEXT NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'paused', 'completed')),
  source TEXT NOT NULL DEFAULT 'week13_seed',
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS community_starter_requests_category_idx
  ON public.community_starter_requests (category);

CREATE INDEX IF NOT EXISTS community_starter_requests_tags_idx
  ON public.community_starter_requests USING GIN (tags);

CREATE INDEX IF NOT EXISTS community_starter_requests_joinable_idx
  ON public.community_starter_requests (allow_join_need, status, created_at DESC);

ALTER TABLE public.community_starter_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Community starter requests are viewable by everyone." ON public.community_starter_requests;
CREATE POLICY "Community starter requests are viewable by everyone."
  ON public.community_starter_requests
  FOR SELECT
  USING (true);

REVOKE INSERT, UPDATE, DELETE ON public.community_starter_requests FROM anon, authenticated;
GRANT SELECT ON public.community_starter_requests TO anon, authenticated;

CREATE OR REPLACE FUNCTION public.set_community_starter_request_tag_credit_bonus()
RETURNS trigger AS $$
BEGIN
  NEW.tags := COALESCE(NEW.tags, '{}'::TEXT[]);
  NEW.tag_credit_bonus := public.calculate_tag_credit_bonus(NEW.tags);
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_community_starter_request_tag_credit_bonus_trigger ON public.community_starter_requests;
CREATE TRIGGER set_community_starter_request_tag_credit_bonus_trigger
  BEFORE INSERT OR UPDATE OF tags ON public.community_starter_requests
  FOR EACH ROW EXECUTE PROCEDURE public.set_community_starter_request_tag_credit_bonus();

INSERT INTO public.community_starter_requests (
  title,
  short_description,
  full_description,
  category,
  tags,
  difficulty,
  estimated_people_who_may_benefit,
  community_request,
  allow_join_need,
  join_count,
  helper_count,
  goodwill_impact_score
)
SELECT
  item.title,
  item.short_description,
  item.full_description,
  item.category,
  item.tags,
  item.difficulty,
  item.estimated_people_who_may_benefit,
  item.community_request,
  item.allow_join_need,
  item.join_count,
  item.helper_count,
  item.goodwill_impact_score
FROM jsonb_to_recordset($week13_requests$
[
  {"title":"Resume Review Support","short_description":"Get simple feedback on resumes before applying.","full_description":"Many students and early professionals are unsure if their resume is clear enough for internships, placements, or first jobs. Join this need if you want friendly resume review support from volunteers.","category":"Career","tags":["resume","career","placements"],"difficulty":"low","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":18,"helper_count":4,"goodwill_impact_score":42},
  {"title":"First-Year Engineering Mathematics Help","short_description":"A shared help group for common engineering math doubts.","full_description":"First-year engineering students often face similar questions in calculus, matrices, and differential equations. Join this need to learn together and get guided help.","category":"Education","tags":["engineering","mathematics","students"],"difficulty":"medium","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":26,"helper_count":5,"goodwill_impact_score":55},
  {"title":"Internship Guidance Session","short_description":"Help students understand how to find internships.","full_description":"Many college students want internships but do not know where to search, how to apply, or how to write a first message. Join this need for practical guidance.","category":"Career","tags":["internship","placement","career"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":31,"helper_count":6,"goodwill_impact_score":61},
  {"title":"Blood Donation Awareness Drive","short_description":"Learn basics of safe blood donation and local awareness.","full_description":"Communities benefit when more people understand blood donation eligibility, safety, and how to find verified drives. Join this need to spread awareness responsibly.","category":"Blood Donation Awareness","tags":["blood","donation","awareness"],"difficulty":"low","estimated_people_who_may_benefit":"50-300 people","community_request":true,"allow_join_need":true,"join_count":22,"helper_count":3,"goodwill_impact_score":58},
  {"title":"Python Programming Study Group","short_description":"A beginner-friendly Python learning group.","full_description":"Students and job seekers often want a practical first programming language. Join this need if you want to learn Python basics with peers and helpers.","category":"Technology","tags":["python","coding","learning"],"difficulty":"medium","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":35,"helper_count":7,"goodwill_impact_score":67},
  {"title":"College Notes Sharing Circle","short_description":"Share useful notes for common college subjects.","full_description":"Many students miss classes or struggle to organize study material before exams. Join this need to request or share helpful notes for common subjects.","category":"Education","tags":["notes","college","exams"],"difficulty":"low","estimated_people_who_may_benefit":"40-250 people","community_request":true,"allow_join_need":true,"join_count":29,"helper_count":4,"goodwill_impact_score":48},
  {"title":"Public Speaking Practice","short_description":"Practice speaking for class, interviews, and events.","full_description":"Students and young professionals often need a safe space to practice introductions, presentations, and group discussion speaking. Join this need to practice together.","category":"Skill Development","tags":["public-speaking","confidence","communication"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":14,"helper_count":3,"goodwill_impact_score":39},
  {"title":"LinkedIn Profile Cleanup","short_description":"Improve LinkedIn basics for job and internship search.","full_description":"A clear LinkedIn profile can help students and professionals be discovered. Join this need for help with headlines, summaries, experience sections, and profile hygiene.","category":"Career","tags":["linkedin","career","networking"],"difficulty":"low","estimated_people_who_may_benefit":"15-120 people","community_request":true,"allow_join_need":true,"join_count":17,"helper_count":2,"goodwill_impact_score":36},
  {"title":"UPI Safety Awareness","short_description":"Learn safe habits for UPI and payment apps.","full_description":"Digital payment scams can affect families, students, and small shops. Join this need to learn simple safety habits and help others avoid common mistakes.","category":"Financial Literacy","tags":["upi","safety","digital-payments"],"difficulty":"low","estimated_people_who_may_benefit":"50-400 people","community_request":true,"allow_join_need":true,"join_count":24,"helper_count":3,"goodwill_impact_score":62},
  {"title":"Aadhaar Update Help","short_description":"Guidance for understanding Aadhaar update steps.","full_description":"People often need help understanding documents, appointment steps, and official links for Aadhaar updates. Join this need for general guidance and peer support.","category":"Government Services","tags":["aadhaar","documents","government"],"difficulty":"low","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":19,"helper_count":2,"goodwill_impact_score":44},
  {"title":"Scholarship Application Help","short_description":"Support students filling scholarship forms.","full_description":"Many eligible students miss scholarships because forms and documents feel confusing. Join this need to get or offer help with checking requirements and deadlines.","category":"Education","tags":["scholarship","forms","students"],"difficulty":"medium","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":21,"helper_count":3,"goodwill_impact_score":52},
  {"title":"Interview Mock Practice","short_description":"Practice common interview questions with volunteers.","full_description":"First interviews can feel stressful without practice. Join this need to do mock introductions, HR questions, and basic technical discussion in a supportive setting.","category":"Career","tags":["interview","practice","jobs"],"difficulty":"medium","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":28,"helper_count":5,"goodwill_impact_score":63},
  {"title":"Excel Basics for Work","short_description":"Learn simple Excel skills for office and college tasks.","full_description":"Basic spreadsheet skills help with assignments, reports, budgets, and entry-level work. Join this need to learn formulas, tables, sorting, and clean formatting.","category":"Skill Development","tags":["excel","office","skills"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":20,"helper_count":4,"goodwill_impact_score":46},
  {"title":"Mental Health Check-In Circle","short_description":"A calm peer circle for stress and exam pressure.","full_description":"Students and young professionals often carry stress quietly. Join this need for a non-clinical peer check-in space focused on listening, routine, and support resources.","category":"Mental Wellbeing","tags":["stress","peer-support","wellbeing"],"difficulty":"medium","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":2,"goodwill_impact_score":47},
  {"title":"Local Cleanup Weekend","short_description":"Organize a small neighborhood cleanup activity.","full_description":"Many areas need simple community cleanup around streets, parks, or college spaces. Join this need if you want to volunteer or coordinate a small cleanup.","category":"Environment","tags":["cleanup","environment","local"],"difficulty":"medium","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":16,"helper_count":5,"goodwill_impact_score":59},
  {"title":"College Club Volunteer Pool","short_description":"Find volunteers for student club activities.","full_description":"Student clubs often need help with registrations, event desks, posters, and coordination. Join this need to offer or request volunteer support for campus activities.","category":"Volunteering","tags":["college","volunteers","events"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":4,"goodwill_impact_score":34},
  {"title":"Bus Route Sharing Help","short_description":"Share reliable local bus and metro route tips.","full_description":"New students and workers often struggle with daily routes in a new city. Join this need to ask for or share practical public transport guidance.","category":"Transportation","tags":["bus","metro","commute"],"difficulty":"low","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":23,"helper_count":3,"goodwill_impact_score":41},
  {"title":"Exam Form Reminder Circle","short_description":"Help students track common exam form deadlines.","full_description":"Students can miss exam forms because deadline information is scattered. Join this need to share reminders and official links for common college and entrance exams.","category":"Education","tags":["exams","deadlines","forms"],"difficulty":"low","estimated_people_who_may_benefit":"50-300 people","community_request":true,"allow_join_need":true,"join_count":33,"helper_count":3,"goodwill_impact_score":57},
  {"title":"Healthy Eating on a Budget","short_description":"Share affordable meal ideas for students and families.","full_description":"Eating well can feel difficult on a limited budget. Join this need to exchange simple, low-cost, locally available meal ideas and planning tips.","category":"Health Awareness","tags":["nutrition","budget","health"],"difficulty":"low","estimated_people_who_may_benefit":"40-250 people","community_request":true,"allow_join_need":true,"join_count":15,"helper_count":2,"goodwill_impact_score":37},
  {"title":"Food Sharing Coordination","short_description":"Coordinate safe surplus food sharing in a locality.","full_description":"Small events and homes sometimes have surplus food that can be shared responsibly. Join this need to coordinate safe, timely, and local food support.","category":"Food Support","tags":["food","sharing","community"],"difficulty":"medium","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":3,"goodwill_impact_score":50},
  {"title":"Elderly Phone Setup Help","short_description":"Help seniors with basic phone settings and apps.","full_description":"Older community members may need patient help with contacts, video calls, UPI safety, and app settings. Join this need to request or offer phone setup support.","category":"Elderly Assistance","tags":["elderly","phone","digital-help"],"difficulty":"low","estimated_people_who_may_benefit":"10-70 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":2,"goodwill_impact_score":43},
  {"title":"GST Basics for Small Sellers","short_description":"Understand basic GST concepts for micro-businesses.","full_description":"Small sellers and student entrepreneurs often need plain-language GST awareness before speaking to a professional. Join this need for beginner-friendly guidance.","category":"Entrepreneurship","tags":["gst","small-business","finance"],"difficulty":"medium","estimated_people_who_may_benefit":"15-90 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":1,"goodwill_impact_score":31},
  {"title":"Digital Portfolio Setup","short_description":"Build a simple portfolio for projects and work samples.","full_description":"Students, designers, developers, and freelancers benefit from a clean project portfolio. Join this need to learn what to include and how to present work.","category":"Career","tags":["portfolio","projects","career"],"difficulty":"medium","estimated_people_who_may_benefit":"15-110 people","community_request":true,"allow_join_need":true,"join_count":16,"helper_count":3,"goodwill_impact_score":40},
  {"title":"English Conversation Practice","short_description":"Practice everyday English in a friendly group.","full_description":"Many learners need a low-pressure space to practice English for interviews, college, and work. Join this need to speak, listen, and improve together.","category":"Skill Development","tags":["english","communication","practice"],"difficulty":"medium","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":27,"helper_count":4,"goodwill_impact_score":56},
  {"title":"College Fresher Orientation Help","short_description":"Help freshers understand campus basics and routines.","full_description":"New college students often need help with departments, IDs, hostels, libraries, and local services. Join this need to ask questions or guide freshers.","category":"Education","tags":["freshers","college","orientation"],"difficulty":"low","estimated_people_who_may_benefit":"40-250 people","community_request":true,"allow_join_need":true,"join_count":25,"helper_count":5,"goodwill_impact_score":49},
  {"title":"Basic Computer Literacy Help","short_description":"Learn computer basics for forms, email, and documents.","full_description":"Many people need simple computer confidence for online forms, email, PDFs, and document editing. Join this need to learn or help with basics.","category":"Technology","tags":["computer","digital-literacy","basics"],"difficulty":"low","estimated_people_who_may_benefit":"30-220 people","community_request":true,"allow_join_need":true,"join_count":18,"helper_count":3,"goodwill_impact_score":45},
  {"title":"Women Safety Resource Map","short_description":"Collect verified safety resources for local areas.","full_description":"Communities can benefit from a shared list of helplines, safe transport tips, and trusted local resources. Join this need to contribute verified information.","category":"Community Events","tags":["safety","women","resources"],"difficulty":"medium","estimated_people_who_may_benefit":"50-500 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":54},
  {"title":"Campus Lost and Found Help","short_description":"Create a simple support thread for lost items.","full_description":"College campuses often need a common place to report lost IDs, keys, books, and chargers. Join this need to help connect people with found items.","category":"Community Events","tags":["campus","lost-found","students"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":7,"helper_count":1,"goodwill_impact_score":22},
  {"title":"First Aid Awareness Session","short_description":"Learn basic first aid awareness for daily situations.","full_description":"Basic first aid awareness can help people respond calmly until professional help arrives. Join this need for general awareness and resource sharing.","category":"Health Awareness","tags":["first-aid","awareness","safety"],"difficulty":"medium","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":14,"helper_count":2,"goodwill_impact_score":51},
  {"title":"Hostel Essentials Sharing","short_description":"Share checklists for students moving into hostels.","full_description":"Students moving into hostels often forget basic items or overpack. Join this need to exchange practical packing lists and local buying tips.","category":"Education","tags":["hostel","students","checklist"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":1,"goodwill_impact_score":27},
  {"title":"Coding Interview Basics","short_description":"Practice beginner coding interview patterns.","full_description":"Many students preparing for placements need structured practice with arrays, strings, logic, and explanations. Join this need to learn with peers.","category":"Technology","tags":["coding","interview","placements"],"difficulty":"high","estimated_people_who_may_benefit":"20-130 people","community_request":true,"allow_join_need":true,"join_count":19,"helper_count":4,"goodwill_impact_score":60},
  {"title":"Budget Planning for Students","short_description":"Learn how to manage monthly student expenses.","full_description":"Students living away from home often need help planning rent, food, travel, and emergency savings. Join this need for practical budgeting support.","category":"Financial Literacy","tags":["budget","students","money"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":17,"helper_count":2,"goodwill_impact_score":38},
  {"title":"Startup Idea Feedback Circle","short_description":"Get early feedback on small business ideas.","full_description":"Students and young professionals often have ideas but need honest feedback before spending money. Join this need to discuss problems, users, and next steps.","category":"Entrepreneurship","tags":["startup","feedback","ideas"],"difficulty":"medium","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":2,"goodwill_impact_score":35},
  {"title":"Local Job Alerts Sharing","short_description":"Share verified entry-level local job openings.","full_description":"Many young workers depend on local referrals and timely openings. Join this need to share verified job leads without spam or fake placement claims.","category":"Career","tags":["jobs","local","alerts"],"difficulty":"low","estimated_people_who_may_benefit":"40-300 people","community_request":true,"allow_join_need":true,"join_count":30,"helper_count":3,"goodwill_impact_score":53},
  {"title":"Tree Plantation Volunteer Group","short_description":"Coordinate volunteers for small plantation activities.","full_description":"Local parks, campuses, and societies sometimes need volunteers for plantation and follow-up watering. Join this need to support practical green efforts.","category":"Environment","tags":["trees","volunteering","environment"],"difficulty":"medium","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":4,"goodwill_impact_score":46},
  {"title":"Exam Anxiety Peer Support","short_description":"Share routines and support for exam stress.","full_description":"Exam pressure can affect sleep, focus, and confidence. Join this need for peer support, planning tips, and healthy routines before exams.","category":"Mental Wellbeing","tags":["exam-stress","students","wellbeing"],"difficulty":"medium","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":18,"helper_count":2,"goodwill_impact_score":44},
  {"title":"Senior Citizen Form Help","short_description":"Assist seniors with common online service forms.","full_description":"Many seniors need patient support reading forms, uploading documents, and understanding official portals. Join this need to request or offer careful assistance.","category":"Elderly Assistance","tags":["elderly","forms","government"],"difficulty":"medium","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":2,"goodwill_impact_score":40},
  {"title":"Waste Segregation Awareness","short_description":"Promote simple wet and dry waste habits.","full_description":"Housing societies and hostels often need reminders and clear examples for waste segregation. Join this need to share posters, tips, and local practices.","category":"Environment","tags":["waste","segregation","awareness"],"difficulty":"low","estimated_people_who_may_benefit":"50-350 people","community_request":true,"allow_join_need":true,"join_count":15,"helper_count":3,"goodwill_impact_score":43},
  {"title":"Freelancing Basics Q&A","short_description":"Understand beginner freelancing setup and client basics.","full_description":"New freelancers need help with profiles, scope, pricing, and safe client communication. Join this need for practical beginner guidance.","category":"Entrepreneurship","tags":["freelancing","clients","income"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":16,"helper_count":2,"goodwill_impact_score":37},
  {"title":"Free Learning Resources List","short_description":"Collect useful free courses and learning links.","full_description":"Students often waste time searching for quality free resources. Join this need to share practical links for coding, English, finance, design, and exams.","category":"Education","tags":["free-resources","learning","students"],"difficulty":"low","estimated_people_who_may_benefit":"100-500 people","community_request":true,"allow_join_need":true,"join_count":41,"helper_count":5,"goodwill_impact_score":66},
  {"title":"Canva Poster Help","short_description":"Help community groups make basic event posters.","full_description":"Student clubs and local groups often need simple posters for events, drives, and notices. Join this need for basic Canva design support.","category":"Skill Development","tags":["canva","design","events"],"difficulty":"low","estimated_people_who_may_benefit":"15-90 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":30},
  {"title":"Local Language Translation Help","short_description":"Translate simple notices for community reach.","full_description":"Important notices are more useful when available in local languages. Join this need to request or offer simple translations for community messages.","category":"Volunteering","tags":["translation","local-language","community"],"difficulty":"medium","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":2,"goodwill_impact_score":39},
  {"title":"Document Scanning Support","short_description":"Help people scan and organize documents clearly.","full_description":"Applications often need clear PDFs of documents. Join this need to learn or help with scanning, naming files, compressing PDFs, and safe sharing.","category":"Technology","tags":["documents","scanning","pdf"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":14,"helper_count":2,"goodwill_impact_score":32},
  {"title":"PAN Application Guidance","short_description":"Understand the basic PAN application process.","full_description":"Many students and first-time earners need PAN for banking, work, or tax documents. Join this need for general guidance and official process awareness.","category":"Government Services","tags":["pan","documents","government"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":18,"helper_count":2,"goodwill_impact_score":41},
  {"title":"Bank Account Basics","short_description":"Learn basics of savings accounts and safe banking.","full_description":"Young adults opening first accounts often need simple explanations of fees, minimum balance, debit cards, and account safety. Join this need for awareness.","category":"Financial Literacy","tags":["banking","savings","students"],"difficulty":"low","estimated_people_who_may_benefit":"30-220 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":2,"goodwill_impact_score":35},
  {"title":"Menstrual Health Awareness","short_description":"Share respectful menstrual health awareness resources.","full_description":"Many students and communities benefit from accurate, stigma-free menstrual health awareness. Join this need to share resources and support practical conversations.","category":"Health Awareness","tags":["menstrual-health","awareness","students"],"difficulty":"medium","estimated_people_who_may_benefit":"40-300 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":2,"goodwill_impact_score":49},
  {"title":"Library Book Exchange","short_description":"Coordinate book sharing for students and readers.","full_description":"Textbooks and reference books can be expensive. Join this need to share, borrow, or donate useful books within a college or locality.","category":"Education","tags":["books","exchange","students"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":16,"helper_count":2,"goodwill_impact_score":33},
  {"title":"Public Transport Safety Tips","short_description":"Share safe commuting tips for daily travel.","full_description":"Students and workers commuting daily can benefit from route planning, timing, and safety tips. Join this need to exchange local commute guidance.","category":"Transportation","tags":["commute","safety","transport"],"difficulty":"low","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":1,"goodwill_impact_score":29},
  {"title":"Local Blood Bank Info List","short_description":"Collect verified blood bank and drive information.","full_description":"Families and communities need reliable awareness about verified blood banks and donation drives. Join this need to maintain a useful local information list.","category":"Blood Donation Awareness","tags":["blood-bank","donation","verified-info"],"difficulty":"medium","estimated_people_who_may_benefit":"50-400 people","community_request":true,"allow_join_need":true,"join_count":15,"helper_count":2,"goodwill_impact_score":52},
  {"title":"Community Sports Meetup","short_description":"Organize casual sports meetups for wellbeing.","full_description":"Sports can help students and residents build routine, fitness, and friendships. Join this need to coordinate casual, inclusive community sports sessions.","category":"Community Events","tags":["sports","meetup","wellbeing"],"difficulty":"low","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":2,"goodwill_impact_score":28},
  {"title":"Job Referral Etiquette Help","short_description":"Learn how to ask for referrals respectfully.","full_description":"Many job seekers want referrals but feel unsure how to approach people. Join this need for examples, message review, and basic networking etiquette.","category":"Career","tags":["referrals","jobs","networking"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":19,"helper_count":3,"goodwill_impact_score":43},
  {"title":"GitHub Basics for Students","short_description":"Learn repositories, commits, and project sharing.","full_description":"Students applying for tech roles often need GitHub basics. Join this need to learn how to upload projects, write README files, and share links.","category":"Technology","tags":["github","coding","students"],"difficulty":"medium","estimated_people_who_may_benefit":"20-140 people","community_request":true,"allow_join_need":true,"join_count":24,"helper_count":4,"goodwill_impact_score":58},
  {"title":"Local NGO Volunteer Discovery","short_description":"Find nearby volunteering opportunities responsibly.","full_description":"People often want to volunteer but do not know which local groups need help. Join this need to share verified opportunities and basic expectations.","category":"Volunteering","tags":["ngo","volunteering","local"],"difficulty":"low","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":17,"helper_count":3,"goodwill_impact_score":47},
  {"title":"Emergency Contact Card Setup","short_description":"Create simple emergency contact cards for families.","full_description":"Families, seniors, and students can benefit from a small emergency contact card with essential numbers. Join this need to prepare and share templates.","category":"Health Awareness","tags":["emergency","family","safety"],"difficulty":"low","estimated_people_who_may_benefit":"50-300 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":45},
  {"title":"Tuition Support for School Basics","short_description":"Help learners with common school subject doubts.","full_description":"School students often need occasional help with math, science, English, or homework concepts. Join this need to request or offer basic academic support.","category":"Education","tags":["school","tuition","homework"],"difficulty":"medium","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":14,"helper_count":3,"goodwill_impact_score":46},
  {"title":"No-Code Website Help","short_description":"Build simple pages using no-code tools.","full_description":"Small clubs, projects, and local businesses sometimes need a simple web presence. Join this need to learn or help with no-code website setup.","category":"Technology","tags":["no-code","website","small-business"],"difficulty":"medium","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":1,"goodwill_impact_score":25},
  {"title":"Petrol Cost Carpool Planning","short_description":"Coordinate shared travel for repeated routes.","full_description":"Students and workers traveling similar routes can save money and reduce congestion with careful planning. Join this need to discuss safe shared commute options.","category":"Transportation","tags":["carpool","commute","cost-sharing"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":7,"helper_count":1,"goodwill_impact_score":24},
  {"title":"Healthy Sleep Routine Support","short_description":"Build better sleep routines during busy weeks.","full_description":"Late-night study and work routines can affect health and focus. Join this need to share realistic sleep hygiene tips and accountability.","category":"Mental Wellbeing","tags":["sleep","routine","wellbeing"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":1,"goodwill_impact_score":34},
  {"title":"Local Festival Volunteer Team","short_description":"Coordinate volunteers for festival community tasks.","full_description":"Local festivals often need help with queues, water desks, cleanliness, and directions. Join this need to support safe and organized community events.","category":"Community Events","tags":["festival","volunteers","local"],"difficulty":"medium","estimated_people_who_may_benefit":"50-400 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":3,"goodwill_impact_score":44},
  {"title":"Food Packet Distribution Help","short_description":"Coordinate volunteers for simple food packet support.","full_description":"Local groups may need help packing, counting, or distributing food packets responsibly. Join this need to volunteer or request coordination support.","category":"Food Support","tags":["food","distribution","volunteers"],"difficulty":"medium","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":4,"goodwill_impact_score":57},
  {"title":"Insurance Basics Awareness","short_description":"Understand basic health and term insurance concepts.","full_description":"Families and young professionals often find insurance confusing. Join this need for plain-language awareness about common terms, questions, and comparison basics.","category":"Financial Literacy","tags":["insurance","family","finance"],"difficulty":"medium","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":1,"goodwill_impact_score":33},
  {"title":"MS Word Document Help","short_description":"Learn formatting for resumes, letters, and reports.","full_description":"Many students and job seekers need clean document formatting. Join this need for help with margins, tables, headings, PDFs, and simple templates.","category":"Skill Development","tags":["ms-word","documents","formatting"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":29},
  {"title":"College Project Team Finder","short_description":"Find teammates for practical college projects.","full_description":"Students often need project teammates with complementary skills. Join this need to connect around project ideas, roles, and timelines.","category":"Education","tags":["projects","teamwork","college"],"difficulty":"medium","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":15,"helper_count":2,"goodwill_impact_score":36},
  {"title":"App Install Help for Seniors","short_description":"Help seniors install and understand essential apps.","full_description":"Seniors may need support installing video call, banking, health, and transport apps safely. Join this need to request or offer patient assistance.","category":"Elderly Assistance","tags":["elderly","apps","support"],"difficulty":"low","estimated_people_who_may_benefit":"10-70 people","community_request":true,"allow_join_need":true,"join_count":6,"helper_count":2,"goodwill_impact_score":35},
  {"title":"College Placement Roadmap","short_description":"Understand placement preparation steps by semester.","full_description":"Students often need a simple roadmap for aptitude, projects, resumes, and interviews. Join this need to learn from seniors and volunteers.","category":"Career","tags":["placements","roadmap","college"],"difficulty":"medium","estimated_people_who_may_benefit":"30-220 people","community_request":true,"allow_join_need":true,"join_count":32,"helper_count":5,"goodwill_impact_score":64},
  {"title":"Cyber Safety for Families","short_description":"Share simple online safety practices for families.","full_description":"Families can avoid many scams by learning safe passwords, OTP caution, privacy settings, and suspicious link habits. Join this need for awareness.","category":"Technology","tags":["cyber-safety","family","awareness"],"difficulty":"low","estimated_people_who_may_benefit":"50-400 people","community_request":true,"allow_join_need":true,"join_count":21,"helper_count":3,"goodwill_impact_score":59},
  {"title":"Local Water Saving Ideas","short_description":"Collect practical water-saving actions for homes.","full_description":"Hostels, homes, and societies can reduce water waste with simple habits and repairs. Join this need to share ideas and local action steps.","category":"Environment","tags":["water","conservation","local"],"difficulty":"low","estimated_people_who_may_benefit":"50-350 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":1,"goodwill_impact_score":31},
  {"title":"Small Business WhatsApp Catalog Help","short_description":"Help local sellers create basic WhatsApp catalogs.","full_description":"Small sellers can show products more clearly through simple catalogs. Join this need to learn or help with photos, descriptions, and setup.","category":"Entrepreneurship","tags":["whatsapp","small-business","catalog"],"difficulty":"low","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":1,"goodwill_impact_score":26},
  {"title":"RTI Awareness Basics","short_description":"Learn what RTI is and when it may help.","full_description":"Citizens may benefit from basic awareness of the Right to Information process and responsible use. Join this need for general, non-legal guidance.","category":"Government Services","tags":["rti","citizen-services","awareness"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":5,"helper_count":1,"goodwill_impact_score":23},
  {"title":"Peer Accountability Study Room","short_description":"Join a quiet study accountability group.","full_description":"Many learners study better with a shared routine and check-ins. Join this need to set goals, attend focused sessions, and stay consistent.","category":"Education","tags":["study","accountability","students"],"difficulty":"low","estimated_people_who_may_benefit":"25-180 people","community_request":true,"allow_join_need":true,"join_count":22,"helper_count":2,"goodwill_impact_score":42},
  {"title":"College Event Anchor Practice","short_description":"Practice anchoring and hosting for events.","full_description":"Students hosting college events often need script and stage practice. Join this need to practice introductions, transitions, and confident delivery.","category":"Skill Development","tags":["anchoring","events","speaking"],"difficulty":"medium","estimated_people_who_may_benefit":"10-70 people","community_request":true,"allow_join_need":true,"join_count":7,"helper_count":1,"goodwill_impact_score":21},
  {"title":"Basic Tax Filing Awareness","short_description":"Understand basic income tax filing concepts.","full_description":"First-time earners often feel confused about Form 16, deductions, and filing timelines. Join this need for beginner awareness before professional help.","category":"Financial Literacy","tags":["tax","first-job","finance"],"difficulty":"medium","estimated_people_who_may_benefit":"20-140 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":1,"goodwill_impact_score":32},
  {"title":"Local Donation Drive Sorting","short_description":"Help sort clothes, books, and supplies for donation.","full_description":"Donation drives need careful sorting so items are useful and respectful. Join this need to volunteer for sorting, packing, or basic inventory.","category":"Volunteering","tags":["donation-drive","sorting","volunteers"],"difficulty":"medium","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":3,"goodwill_impact_score":48},
  {"title":"Anti-Litter Campus Pledge","short_description":"Start a small campus anti-litter action group.","full_description":"A cleaner campus starts with repeated small habits. Join this need to support anti-litter reminders, bin mapping, and cleanup coordination.","category":"Environment","tags":["campus","anti-litter","cleanup"],"difficulty":"low","estimated_people_who_may_benefit":"40-250 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":2,"goodwill_impact_score":33},
  {"title":"Dengue Prevention Awareness","short_description":"Share mosquito prevention reminders in communities.","full_description":"Seasonal dengue prevention depends on awareness, clean surroundings, and removing stagnant water. Join this need to spread practical reminders responsibly.","category":"Health Awareness","tags":["dengue","prevention","awareness"],"difficulty":"low","estimated_people_who_may_benefit":"100-500 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":2,"goodwill_impact_score":50},
  {"title":"Community Reading Hour","short_description":"Organize reading time for children and learners.","full_description":"A simple reading hour can help children and young learners build confidence. Join this need to volunteer, read aloud, or coordinate books.","category":"Community Events","tags":["reading","children","community"],"difficulty":"low","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":2,"goodwill_impact_score":36},
  {"title":"Affordable PG Search Tips","short_description":"Share tips for finding safe PGs and rentals.","full_description":"Students and young professionals moving cities need practical tips on rent, deposits, locations, and checks. Join this need to exchange guidance.","category":"Transportation","tags":["pg","housing","relocation"],"difficulty":"medium","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":15,"helper_count":2,"goodwill_impact_score":38},
  {"title":"Simple Website Accessibility Review","short_description":"Help small sites become easier to read and use.","full_description":"Student projects and community websites can improve with readable text, contrast, labels, and mobile checks. Join this need to learn or review basics.","category":"Technology","tags":["accessibility","website","review"],"difficulty":"medium","estimated_people_who_may_benefit":"10-70 people","community_request":true,"allow_join_need":true,"join_count":4,"helper_count":1,"goodwill_impact_score":20},
  {"title":"Small Shop Digital Payments Setup","short_description":"Help small shops understand QR payment basics.","full_description":"Some small shops need help setting up and safely using QR payments. Join this need for beginner guidance and fraud awareness.","category":"Entrepreneurship","tags":["digital-payments","shops","upi"],"difficulty":"low","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":7,"helper_count":1,"goodwill_impact_score":27},
  {"title":"Community Kitchen Volunteer List","short_description":"Build a volunteer list for kitchen support tasks.","full_description":"Food support groups often need help with prep, serving, cleaning, and packing. Join this need to offer time or coordinate volunteer slots.","category":"Food Support","tags":["community-kitchen","food","volunteers"],"difficulty":"medium","estimated_people_who_may_benefit":"30-200 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":3,"goodwill_impact_score":46},
  {"title":"Career Switcher Support Circle","short_description":"Support people exploring a new career path.","full_description":"Changing careers can feel confusing and lonely. Join this need to discuss skills, realistic timelines, portfolio ideas, and first steps.","category":"Career","tags":["career-switch","skills","support"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":34},
  {"title":"Children Homework Buddy Group","short_description":"Volunteer for light homework support sessions.","full_description":"Some children need regular encouragement with reading, math, and homework routines. Join this need to request or offer friendly homework support.","category":"Volunteering","tags":["children","homework","volunteers"],"difficulty":"medium","estimated_people_who_may_benefit":"15-90 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":3,"goodwill_impact_score":45},
  {"title":"Basic Data Entry Training","short_description":"Learn data entry habits for entry-level work.","full_description":"Entry-level work often needs accuracy, typing discipline, spreadsheets, and file organization. Join this need to practice basic data entry skills.","category":"Skill Development","tags":["data-entry","typing","jobs"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":14,"helper_count":2,"goodwill_impact_score":32},
  {"title":"Voter Registration Awareness","short_description":"Share official voter registration process awareness.","full_description":"Eligible citizens may need help understanding registration steps, official portals, and document basics. Join this need for awareness and reminder sharing.","category":"Government Services","tags":["voter-id","registration","awareness"],"difficulty":"low","estimated_people_who_may_benefit":"40-300 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":1,"goodwill_impact_score":30},
  {"title":"Safe Blood Donation Myth Busting","short_description":"Discuss common myths around blood donation.","full_description":"Many people hesitate to donate blood because of myths or unclear information. Join this need to share verified awareness and encourage informed choices.","category":"Blood Donation Awareness","tags":["blood","myths","health-awareness"],"difficulty":"low","estimated_people_who_may_benefit":"50-350 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":2,"goodwill_impact_score":42},
  {"title":"Personal Finance Book Club","short_description":"Read and discuss beginner finance ideas together.","full_description":"Young adults can build better money habits through shared reading and discussion. Join this need for simple book, article, or video discussions.","category":"Financial Literacy","tags":["finance","book-club","learning"],"difficulty":"low","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":6,"helper_count":1,"goodwill_impact_score":22},
  {"title":"College Lab Record Help","short_description":"Help students understand lab record formatting.","full_description":"Students often lose marks for unclear lab records or missing sections. Join this need for formatting examples and general record-writing support.","category":"Education","tags":["lab-record","college","students"],"difficulty":"low","estimated_people_who_may_benefit":"20-130 people","community_request":true,"allow_join_need":true,"join_count":13,"helper_count":1,"goodwill_impact_score":25},
  {"title":"Local Park Walking Group","short_description":"Start a simple walking group for routine and safety.","full_description":"Walking with a group can help people build routine and feel safer in local parks. Join this need to coordinate timings and routes.","category":"Health Awareness","tags":["walking","fitness","community"],"difficulty":"low","estimated_people_who_may_benefit":"20-120 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":1,"goodwill_impact_score":24},
  {"title":"Student Travel Pass Guidance","short_description":"Understand local student pass application steps.","full_description":"Students may need help with bus, metro, or railway pass documents and portals. Join this need to share official links and practical tips.","category":"Transportation","tags":["student-pass","transport","documents"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":12,"helper_count":1,"goodwill_impact_score":31},
  {"title":"Simple Video Editing Help","short_description":"Learn basic edits for reels, projects, and events.","full_description":"Students and community groups often need simple video editing for presentations and event recaps. Join this need to learn trimming, captions, and exports.","category":"Skill Development","tags":["video-editing","content","skills"],"difficulty":"medium","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":2,"goodwill_impact_score":28},
  {"title":"Open Source Beginner Circle","short_description":"Help beginners make their first open source steps.","full_description":"Students interested in open source often need help finding beginner issues, using Git, and communicating respectfully. Join this need to learn together.","category":"Technology","tags":["open-source","git","coding"],"difficulty":"high","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":2,"goodwill_impact_score":36},
  {"title":"Local Elder Visit Volunteers","short_description":"Coordinate respectful visits or calls for seniors.","full_description":"Some seniors benefit from friendly check-ins, reading help, or simple conversation. Join this need to coordinate respectful, verified volunteer support.","category":"Elderly Assistance","tags":["elderly","visits","companionship"],"difficulty":"medium","estimated_people_who_may_benefit":"10-60 people","community_request":true,"allow_join_need":true,"join_count":5,"helper_count":2,"goodwill_impact_score":39},
  {"title":"Plastic-Free Event Planning","short_description":"Plan small events with fewer single-use plastics.","full_description":"College and community events can reduce waste with refill stations, reusable plates, and better planning. Join this need to share practical ideas.","category":"Environment","tags":["plastic-free","events","environment"],"difficulty":"medium","estimated_people_who_may_benefit":"30-250 people","community_request":true,"allow_join_need":true,"join_count":6,"helper_count":1,"goodwill_impact_score":26},
  {"title":"Women Returnship Support","short_description":"Support women restarting careers after a break.","full_description":"People returning to work after a break may need confidence, resume framing, and skill refresh support. Join this need for community guidance.","category":"Career","tags":["returnship","women","career"],"difficulty":"medium","estimated_people_who_may_benefit":"10-80 people","community_request":true,"allow_join_need":true,"join_count":7,"helper_count":1,"goodwill_impact_score":30},
  {"title":"Low-Cost Tiffin Info Sharing","short_description":"Share affordable local tiffin and meal options.","full_description":"Students and workers living away from home often search for reliable food options. Join this need to share affordable local tiffin information.","category":"Food Support","tags":["tiffin","students","food"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":9,"helper_count":1,"goodwill_impact_score":23},
  {"title":"Basic Startup Pitch Practice","short_description":"Practice explaining a startup idea clearly.","full_description":"Early founders need to explain the problem, user, solution, and next step simply. Join this need to practice and improve pitch clarity.","category":"Entrepreneurship","tags":["pitch","startup","practice"],"difficulty":"medium","estimated_people_who_may_benefit":"10-70 people","community_request":true,"allow_join_need":true,"join_count":6,"helper_count":1,"goodwill_impact_score":24},
  {"title":"Common App Troubleshooting Help","short_description":"Help people fix basic app login and settings issues.","full_description":"Many users struggle with app updates, permissions, login, and notifications. Join this need to ask for or offer basic troubleshooting support.","category":"Technology","tags":["apps","troubleshooting","digital-help"],"difficulty":"low","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":11,"helper_count":2,"goodwill_impact_score":29},
  {"title":"Community Notice Drafting Help","short_description":"Write clear notices for societies and student groups.","full_description":"Good notices reduce confusion around events, maintenance, drives, and deadlines. Join this need for help drafting concise community messages.","category":"Skill Development","tags":["writing","notices","community"],"difficulty":"low","estimated_people_who_may_benefit":"15-100 people","community_request":true,"allow_join_need":true,"join_count":5,"helper_count":1,"goodwill_impact_score":19},
  {"title":"Local Health Camp Volunteers","short_description":"Coordinate non-medical volunteers for health camps.","full_description":"Health camps often need help with registration, queues, water, and directions. Join this need to volunteer for safe, non-medical support tasks.","category":"Volunteering","tags":["health-camp","volunteers","community"],"difficulty":"medium","estimated_people_who_may_benefit":"50-300 people","community_request":true,"allow_join_need":true,"join_count":8,"helper_count":3,"goodwill_impact_score":49},
  {"title":"Exam Result Support Circle","short_description":"Offer peer support after stressful exam results.","full_description":"Results season can be emotionally difficult for students and families. Join this need for calm peer support, next-step planning, and encouragement.","category":"Mental Wellbeing","tags":["results","students","support"],"difficulty":"medium","estimated_people_who_may_benefit":"20-150 people","community_request":true,"allow_join_need":true,"join_count":10,"helper_count":1,"goodwill_impact_score":36}
]
$week13_requests$::jsonb) AS item(
  title TEXT,
  short_description TEXT,
  full_description TEXT,
  category TEXT,
  tags TEXT[],
  difficulty TEXT,
  estimated_people_who_may_benefit TEXT,
  community_request BOOLEAN,
  allow_join_need BOOLEAN,
  join_count INTEGER,
  helper_count INTEGER,
  goodwill_impact_score INTEGER
)
ON CONFLICT (title) DO UPDATE SET
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  category = EXCLUDED.category,
  tags = EXCLUDED.tags,
  difficulty = EXCLUDED.difficulty,
  estimated_people_who_may_benefit = EXCLUDED.estimated_people_who_may_benefit,
  community_request = EXCLUDED.community_request,
  allow_join_need = EXCLUDED.allow_join_need,
  join_count = EXCLUDED.join_count,
  helper_count = EXCLUDED.helper_count,
  goodwill_impact_score = EXCLUDED.goodwill_impact_score,
  updated_at = now();
