/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppNewRouteImport } from './routes/app.new'
import { Route as AppHelpersRouteImport } from './routes/app.helpers'
import { Route as AppUIdRouteImport } from './routes/app.u.$id'
import { Route as AppStoriesNewRouteImport } from './routes/app.stories.new'
import { Route as AppRequestsIdRouteImport } from './routes/app.requests.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNewRoute = AppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpersRoute = AppHelpersRouteImport.update({
  id: '/helpers',
  path: '/helpers',
  getParentRoute: () => AppRoute,
} as any)
const AppUIdRoute = AppUIdRouteImport.update({
  id: '/u/$id',
  path: '/u/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppStoriesNewRoute = AppStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsIdRoute = AppRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/helpers': typeof AppHelpersRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/u/$id': typeof AppUIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/helpers': typeof AppHelpersRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app': typeof AppIndexRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/u/$id': typeof AppUIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/helpers': typeof AppHelpersRoute
  '/app/new': typeof AppNewRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/': typeof AppIndexRoute
  '/app/requests/$id': typeof AppRequestsIdRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/u/$id': typeof AppUIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/helpers'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/requests/$id'
    | '/app/stories/new'
    | '/app/u/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/helpers'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app'
    | '/app/requests/$id'
    | '/app/stories/new'
    | '/app/u/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/helpers'
    | '/app/new'
    | '/app/notifications'
    | '/app/profile'
    | '/app/'
    | '/app/requests/$id'
    | '/app/stories/new'
    | '/app/u/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/new': {
      id: '/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/helpers': {
      id: '/app/helpers'
      path: '/helpers'
      fullPath: '/app/helpers'
      preLoaderRoute: typeof AppHelpersRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/u/$id': {
      id: '/app/u/$id'
      path: '/u/$id'
      fullPath: '/app/u/$id'
      preLoaderRoute: typeof AppUIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/stories/new': {
      id: '/app/stories/new'
      path: '/stories/new'
      fullPath: '/app/stories/new'
      preLoaderRoute: typeof AppStoriesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests/$id': {
      id: '/app/requests/$id'
      path: '/requests/$id'
      fullPath: '/app/requests/$id'
      preLoaderRoute: typeof AppRequestsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppHelpersRoute: typeof AppHelpersRoute
  AppNewRoute: typeof AppNewRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppIndexRoute: typeof AppIndexRoute
  AppRequestsIdRoute: typeof AppRequestsIdRoute
  AppStoriesNewRoute: typeof AppStoriesNewRoute
  AppUIdRoute: typeof AppUIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppHelpersRoute: AppHelpersRoute,
  AppNewRoute: AppNewRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProfileRoute: AppProfileRoute,
  AppIndexRoute: AppIndexRoute,
  AppRequestsIdRoute: AppRequestsIdRoute,
  AppStoriesNewRoute: AppStoriesNewRoute,
  AppUIdRoute: AppUIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
