// File generated by FlutterFire CLI & Antigravity.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsITdQ0TeaM6DPizj385Evt5j8Gn1acEc',
    appId: '1:793032968256:web:86f1d3dfae8503be6037a5',
    messagingSenderId: '793032968256',
    projectId: 'goodwill-circle',
    authDomain: 'goodwill-circle.firebaseapp.com',
    storageBucket: 'goodwill-circle.firebasestorage.app',
    measurementId: 'G-J9F03RKK3M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAx6I40Z8yH5tHnHv2vPHrod84hkQPMyk',
    appId: '1:793032968256:android:84ca918ed15e14ee6037a5',
    messagingSenderId: '793032968256',
    projectId: 'goodwill-circle',
    storageBucket: 'goodwill-circle.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAx6I40Z8yH5tHnHv2vPHrod84hkQPMyk',
    appId: '1:793032968256:ios:86f1d3dfae8503be6037a5',
    messagingSenderId: '793032968256',
    projectId: 'goodwill-circle',
    storageBucket: 'goodwill-circle.firebasestorage.app',
    iosBundleId: 'com.goodwillcircle.goodwillCircle',
  );
}
